version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    working_directory: ~/circleci-testcafe
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: show current directory
          command: pwd
      - run:
          name: show directory contents
          command: ls -lrt
      - run:
          name: execute testcafe using chrome
          command: npm run test:chrome
      - store_test_results:
          path: /test-results   
workflows:
  e2e-test:
    jobs:
     - test
