version: 2.1
jobs:
  build:
    working_directory: ~/circleci-testcafe
    steps:
      - checkout
  test:
    working_directory: ~/circleci-testcafe
    docker:
      - image: testcafe/testcafe
      - setup_remote_docker
      - run:
          name: execute testcafe using chromium
          command: docker run -v ${PWD}/tests:/tests -it testcafe/testcafe chromium /tests    
workflows:
  build_test:
    jobs:
     - build
     - test
