version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  test:
    working_directory: ~/circleci-testcafe
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install
      - npm install
      - run:
          name: show current directory
          command: pwd
      - run:
          name: show directory contents
          command: ls -lrt
      - run:
          name: execute testcafe using chrome
          command: npm run test:chrome
      - run:
          name: show directory
          command: pwd
      - run:
          name: list directory contents
          command: ls -lrt
      - store_artifacts:
          path: test-results   
workflows:
  e2e-test:
    jobs:
     - test
