version: 2.1
jobs:
  build:
    working_directory: ~/circleci-testcafe
    docker:
      - image: circleci/python:3.8.3
      - image: testcafe/testcafe:1.18.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: show current directory
          command: pwd
      - run:
          name: show directory contents
          command: ls -lrt
      - run:
          name: execute testcafe using chromium
          command: docker run -v ${PWD}/tests:/tests -it testcafe/testcafe chromium /tests    
workflows:
  build:
    jobs:
     - build
